
TOPDIR := ../..

TARGET_PROGS =
TARGET_PROGS += mainStack 
TARGET_PROGS += stack3test
TARGET_PROGS += maxtest
TARGET_PROGS += max3test
TARGET_PROGS += stack4test 
TARGET_PROGS += stack5test 
TARGET_PROGS += stack7test 
TARGET_PROGS += stack8test 
TARGET_PROGS += stack9test 
TARGET_PROGS += refnonref 
TARGET_PROGS += lazy 
TARGET_PROGS += deducetest1 
TARGET_PROGS += accum1 
TARGET_PROGS += accum2
TARGET_PROGS += accum3
TARGET_PROGS += accum4
TARGET_PROGS += accum5
TARGET_PROGS += accum6
TARGET_PROGS += accum8
TARGET_PROGS += accum0
TARGET_PROGS += elementtype
TARGET_PROGS += isclasst
TARGET_PROGS += namedtmpl
TARGET_PROGS += ebco1
TARGET_PROGS += ebco2

INCDIRS =
INCDIRS += .

CFLAGS_PROG += -DBIT_IS_DEBUG -DBIT_HAS_DEBUG_COLORS
CFLAGS_PROG += -DBIT_IS_STB -std=c++11


BIT_SRCS =
BIT_SRCS += mainStack.cpp
STACK3_SRCS += stack3test.cpp
STACK4_SRCS += stack4test.cpp
STACK5_SRCS += stack5test.cpp
STACK7_SRCS += stack7test.cpp
STACK8_SRCS += stack8test.cpp
STACK9_SRCS += stack9test.cpp
MAX_SRCS += maxtest.cpp
MAX3_SRCS += max3test.cpp
REFNONREF_SRCS += refnonref.cpp
LAZY_SRCS += lazy.cpp
DEDUCETEST1_SRCS += deducetest1.cpp
ACCUM1_SRCS += accum1.cpp
ACCUM2_SRCS += accum2.cpp
ACCUM3_SRCS += accum3.cpp
ACCUM4_SRCS += accum4.cpp
ACCUM5_SRCS += accum5.cpp
ACCUM6_SRCS += accum6.cpp
ACCUM8_SRCS += accum8.cpp
ACCUM0_SRCS += accum0.cpp
ELEMENTTYPE_SRCS += elementtype.cpp
ISCLASST_SRCS += isclasst.cpp
NAMEDTMPL_SRCS += namedtmpl.cpp
EBCO1_SRCS += ebco1.cpp
EBCO2_SRCS += ebco2.cpp

SRCS_mainStack = $(BIT_SRCS)
SRCS_stack3test = $(STACK3_SRCS)
SRCS_stack4test = $(STACK4_SRCS)
SRCS_stack5test = $(STACK5_SRCS)
SRCS_stack7test = $(STACK7_SRCS)
SRCS_stack8test = $(STACK8_SRCS)
SRCS_stack9test = $(STACK9_SRCS)
SRCS_maxtest = $(MAX_SRCS)
SRCS_max3test = $(MAX3_SRCS)
SRCS_refnonref = $(REFNONREF_SRCS)
SRCS_lazy = $(LAZY_SRCS)
SRCS_deducetest1 = $(DEDUCETEST1_SRCS)
SRCS_accum1 = $(ACCUM1_SRCS)
SRCS_accum2 = $(ACCUM2_SRCS)
SRCS_accum3 = $(ACCUM3_SRCS)
SRCS_accum4 = $(ACCUM4_SRCS)
SRCS_accum5 = $(ACCUM5_SRCS)
SRCS_accum6 = $(ACCUM6_SRCS)
SRCS_accum8 = $(ACCUM8_SRCS)
SRCS_accum0 = $(ACCUM0_SRCS)
SRCS_elementtype = $(ELEMENTTYPE_SRCS)
SRCS_isclasst = $(ISCLASST_SRCS)
SRCS_namedtmpl = $(NAMEDTMPL_SRCS)
SRCS_ebco1 = $(EBCO1_SRCS)
SRCS_ebco2 = $(EBCO2_SRCS)

include $(TOPDIR)/jhbuild/Make.Defaults
include $(TOPDIR)/jhbuild/Make.Rules


